AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - vendor/**/*
    - spec/**/*
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
